---
title: "SOSC Descriptive"
author: "Luke Andreesen"
date: "5/16/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message = FALSE}

setwd("/Users/lukeandreesen/Desktop/SOSC Final")

library(rio)
library(here)
library(tidyverse)
library(countrycode)
library(ggplot2)


here::i_am("data/GDP.csv")
gdp <- import( here("data/GDP.csv") )
dim(gdp)


colnames(gdp)[1] <- "Country"
colnames(gdp)[2] <- "Country_Code"
colnames(gdp)[3] <- "GDP"
gdp <- drop_na(gdp, any_of("GDP"))
gdp <- gdp %>% select(-Country)

here::i_am("data/GNI.csv")
gni <- import( here("data/GNI.csv") )
dim(gni)

colnames(gni)[1] <- "Country"
colnames(gni)[2] <- "Country_Code"
colnames(gni)[3] <- "GNI"
gni <- drop_na(gni, any_of("GNI"))
gni <- gni %>% select(-Country)

gdp_gni <- merge(gdp, gni, by = "Country_Code")

here::i_am("data/Female HPV.csv")
female_hpv <- import( here("data/Female HPV.csv") )
dim(female_hpv)

colnames(female_hpv)[1] <- "Country"
colnames(female_hpv)[4] <- "Uncertainty"
colnames(female_hpv)[5] <- "Rate"
colnames(female_hpv)[6] <- "ASR"
colnames(female_hpv)[7] <- "Risk"

female_hpv <- female_hpv %>% select(-Population)
female_hpv <- female_hpv %>% select(-Number)
female_hpv <- female_hpv %>% select(-Uncertainty)
female_hpv <- female_hpv %>% select(-Risk)
female_hpv <- female_hpv %>% select(-Rate)
female_hpv$Country <- countrycode(female_hpv$Country, "country.name", "wb")
female_hpv <- drop_na(female_hpv, any_of("Country"))
colnames(female_hpv)[1] <- "Country_Code"


here::i_am("data/Male HPV.csv")
male_hpv <- import( here("data/Male HPV.csv") )
dim(male_hpv)

colnames(male_hpv)[1] <- "Country"
colnames(male_hpv)[4] <- "Uncertainty"
colnames(male_hpv)[5] <- "Rate"
colnames(male_hpv)[6] <- "ASR"
colnames(male_hpv)[7] <- "Risk"

male_hpv <- male_hpv %>% select(-Population)
male_hpv <- male_hpv %>% select(-Number)
male_hpv <- male_hpv %>% select(-Uncertainty)
male_hpv <- male_hpv %>% select(-Risk)
male_hpv <- male_hpv %>% select(-Rate)
male_hpv$Country <- countrycode(male_hpv$Country, "country.name", "wb")
male_hpv <- drop_na(male_hpv, any_of("Country"))
colnames(male_hpv)[1] <- "Country_Code"

hpv <- merge(female_hpv, male_hpv, by = "Country_Code")
hpv$row_mean <- rowMeans(hpv[ , c(2,3)], na.rm=TRUE)
colnames(hpv)[2] <- "ASR_Female"
colnames(hpv)[3] <- "ASR_Male"
colnames(hpv)[4] <- "ASR_Combined"


here::i_am("data/Testis.csv")
testis <- import( here("data/Testis.csv") )
dim(testis)

colnames(testis)[1] <- "Country"
colnames(testis)[4] <- "Uncertainty"
colnames(testis)[5] <- "Rate"
colnames(testis)[6] <- "ASR"
colnames(testis)[7] <- "Risk"

testis <- testis %>% select(-Population)
testis <- testis %>% select(-Number)
testis <- testis %>% select(-Uncertainty)
testis <- testis %>% select(-Risk)
testis <- testis %>% select(-Rate)

testis$Country <- countrycode(testis$Country, "country.name", "wb")
testis <- drop_na(testis, any_of("Country"))
colnames(testis)[1] <- "Country_Code"

here::i_am("data/Melanoma.csv")
melanoma <- import( here("data/Melanoma.csv") )
dim(melanoma)

colnames(melanoma)[1] <- "Country"
colnames(melanoma)[4] <- "Uncertainty"
colnames(melanoma)[5] <- "Rate"
colnames(melanoma)[6] <- "ASR"
colnames(melanoma)[7] <- "Risk"

melanoma <- melanoma %>% select(-Population)
melanoma <- melanoma %>% select(-Number)
melanoma <- melanoma %>% select(-Uncertainty)
melanoma <- melanoma %>% select(-Risk)
melanoma <- melanoma %>% select(-Rate)

melanoma$Country <- countrycode(melanoma$Country, "country.name", "wb")
melanoma <- drop_na(melanoma, any_of("Country"))
colnames(melanoma)[1] <- "Country_Code"


here::i_am("data/Prostate.csv")
prostate <- import( here("data/Prostate.csv") )
dim(prostate)

colnames(prostate)[1] <- "Country"
colnames(prostate)[4] <- "Uncertainty"
colnames(prostate)[5] <- "Rate"
colnames(prostate)[6] <- "ASR"
colnames(prostate)[7] <- "Risk"

prostate <- prostate %>% select(-Population)
prostate <- prostate %>% select(-Number)
prostate <- prostate %>% select(-Uncertainty)
prostate <- prostate %>% select(-Risk)
prostate <- prostate %>% select(-Rate)

prostate$Country <- countrycode(prostate$Country, "country.name", "wb")
prostate <- drop_na(prostate, any_of("Country"))
colnames(prostate)[1] <- "Country_Code"


here::i_am("data/Thyroid.csv")
thyroid <- import( here("data/Thyroid.csv") )
dim(thyroid)

colnames(thyroid)[1] <- "Country"
colnames(thyroid)[4] <- "Uncertainty"
colnames(thyroid)[5] <- "Rate"
colnames(thyroid)[6] <- "ASR"
colnames(thyroid)[7] <- "Risk"

thyroid <- thyroid %>% select(-Population)
thyroid <- thyroid %>% select(-Number)
thyroid <- thyroid %>% select(-Uncertainty)
thyroid <- thyroid %>% select(-Risk)
thyroid <- thyroid %>% select(-Rate)

thyroid$Country <- countrycode(thyroid$Country, "country.name", "wb")
thyroid <- drop_na(thyroid, any_of("Country"))
colnames(thyroid)[1] <- "Country_Code"


here::i_am("data/Tobacco.csv")
tobacco <- import( here("data/Tobacco.csv") )
dim(tobacco)

colnames(tobacco)[1] <- "Country"
colnames(tobacco)[4] <- "Uncertainty"
colnames(tobacco)[5] <- "Rate"
colnames(tobacco)[6] <- "ASR"
colnames(tobacco)[7] <- "Risk"

tobacco <- tobacco %>% select(-Population)
tobacco <- tobacco %>% select(-Number)
tobacco <- tobacco %>% select(-Uncertainty)
tobacco <- tobacco %>% select(-Risk)
tobacco <- tobacco %>% select(-Rate)

tobacco$Country <- countrycode(tobacco$Country, "country.name", "wb")
tobacco <- drop_na(tobacco, any_of("Country"))
colnames(tobacco)[1] <- "Country_Code"

hpv_wealth <- merge(gdp_gni, hpv, by = "Country_Code")
tetis_wealth <- merge(gdp_gni, testis, by = "Country_Code")
melanoma_wealth <- merge(gdp_gni, melanoma, by = "Country_Code")
prostate_wealth <- merge(gdp_gni, prostate, by = "Country_Code")
thyroid_wealth <- merge(gdp_gni, thyroid, by = "Country_Code")
tobacco_wealth <- merge(gdp_gni, tobacco, by = "Country_Code")

gdp_plot <- ggplot(gdp,aes(x=GDP))+ geom_histogram() + xlab("GDP per Capita") + 
  ylab("Number of Countries")+
  xlim(0,200000)+
  ylim(0,120)+
  scale_y_continuous(breaks = seq(0, 150, by = 10))+
  scale_x_continuous(breaks = seq(0, 200000, by = 25000))+
  ggtitle("GDP per Capita") +
theme(
      plot.title = element_text(hjust = 0.5))
gdp_plot 

gni_plot <- ggplot(gni,aes(x=factor(0),GNI))+geom_boxplot() + ylab("GNI per Capita") + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
gni_plot

hpv_plot <- ggplot(hpv, aes(x = factor(0), y = ASR_Female, ASR_Male, ASR_Combined)) +
  geom_boxplot() +
  ylab("Age Standardized Incidence Rate (per 100,000)") +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        plot.title = element_text(hjust = 0.5))
hpv_plot

testis_plot <- ggplot(testis,aes(x=factor(0), y=testis))+geom_boxplot() +
  ylab("Age Standardized Incidence Rate (per 100,000)") + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        plot.title = element_text(hjust = 0.5))
testis_plot

melanoma_plot <- ggplot(melanoma,aes(x=factor(0), y=melanoma))+
  geom_boxplot() + 
  ylab("Age Standardized Incidence Rate (per 100,000)") + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        plot.title = element_text(hjust = 0.5))
melanoma_plot

prostate_plot <- ggplot(prostate,aes(x=factor(0), y=prostate))+geom_boxplot() + 
  ylab("Age Standardized Incidence Rate (per 100,000)") + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        plot.title = element_text(hjust = 0.5))
prostate_plot

thyroid_plot <- ggplot(thyroid,aes(x=factor(0), y=thyroid))+geom_boxplot() +
  ylab("Age Standardized Incidence Rate (per 100,000)") + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        plot.title = element_text(hjust = 0.5))
thyroid_plot


tobacco_plot <- ggplot(tobacco,aes(x=factor(0), y=tobacco)) +
  geom_boxplot() +
  ylab("Age Standardized Incidence Rate (per 100,000)") + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        plot.title = element_text(hjust = 0.5))
tobacco_plot
```

```{r, warning = FALSE, message = FALSE}
print(fivenum(gdp$GDP))
print(fivenum(gni$GNI))
print(fivenum(hpv$ASR_Combined))
print(fivenum(testis$ASR))
print(fivenum(prostate$ASR))
print(fivenum(tobacco$ASR))
print(fivenum(melanoma$ASR))
print(fivenum(thyroid$ASR))

```
